# Generated by Django 3.2.9 on 2022-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('packet', 'packet'), ('bottle', 'bottle')], max_length=100),
        ),
    ]
