# Generated by Django 3.2.9 on 2022-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('options', 'options'), ('bottle', 'bottle')], max_length=100),
        ),
    ]
